# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3523d20f5e985dc093e41ce6e9bad17b525f80d292e70d1ef9a6a47c0ead5ac7db5717d69112e895aa07e932c6ce34d48a191bae4c6b0bad6198385f0488f8c

test:
  secret_key_base: b95c95350fcd0d57d5e7d11754d06e0160c72eb5b7b915187ce20f8bb7025302a38c0b38cf034a9dc5235882499b4550394b1c9429a69704abfc79b34e7d14f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
